const path = require('path');
const execa = require('execa');
const ora = require('ora');
const fs = require('fs-extra');
const logger = require('../utils/logger');
const configManager = require('../utils/configManager');
const waitForApp = require('../utils/waitForApp');

module.exports = async function run(opts = {}) {
  try {
    const cfg = await configManager.readConfig();
    const dockerDir = path.join(process.cwd(), cfg.dockerDir || '.docker');

    // For run: do not rebuild. Use existing .docker artifacts (or generate docker-compose/.env from templates) and start compose.
    const composePath = path.join(dockerDir, 'docker-compose.yml');
    const envPath = path.join(dockerDir, '.env');

    // Ensure .docker exists
    await fs.ensureDir(dockerDir);

    // Require local build artifacts. `mxtest run` is intended to consume the
    // build output in `.docker/build`. If that folder doesn't exist, abort
    // and instruct the user to run the build step. No image handling or
    // interactive prompts are performed here.
    const buildDir = path.join(dockerDir, 'build');
    const hasBuild = await fs.pathExists(buildDir);
    if (!hasBuild) {
      logger.error('Cannot run: no Docker build artifacts found.');
      logger.info('Run `mxtest build` or `mxtest run-build` to generate Docker artifacts.');
      process.exit(1);
    }

    // Ensure .env exists or write one from template using current config
    if (!await fs.pathExists(envPath)) {
      try {
        const template = await fs.readFile(path.join(__dirname, '..', 'templates', '.env.txt'), 'utf8');
        const content = template.replace(/{{CLIENT_PORT}}/g, String(cfg.clientPort || 8080)).replace(/{{POSTGRES_PORT}}/g, String(cfg.postgresPort || 5432)).replace(/{{APP_URL}}/g, String(cfg.appUrl || 'http://localhost:8080'));
        await fs.writeFile(envPath, content, 'utf8');
        logger.success('Wrote .env into .docker');
      } catch (err) {
        logger.warn('Failed to write .env: ' + String(err));
      }
    }

    // Do not overwrite an existing docker-compose.yml generated by the
    // build process. If the builder didn't create one, that's an error.
    if (!await fs.pathExists(composePath)) {
      logger.error('No docker-compose.yml found in .docker. Run `mxtest build` to generate it.');
      process.exit(1);
    }

    // If we have local build artifacts and a Dockerfile, but the compose
    // references an `image:` (causing Docker to try pulling), rewrite the
    // compose file to prefer a local build context so `docker compose up`
    // does not attempt to pull a remote image.
    const dockerfilePath = path.join(buildDir, 'Dockerfile');
    const hasDockerfile = await fs.pathExists(dockerfilePath);
    if (hasBuild && hasDockerfile) {
      try {
        let composeText = await fs.readFile(composePath, 'utf8');
        // If compose already contains a `build:` block, assume it's correct.
        if (!/^[ \t]*build:/im.test(composeText) && /^[ \t]*image:/im.test(composeText)) {
          // Replace the first image: line with a build block while preserving indentation
          composeText = composeText.replace(/(^[ \t]*)(image:\s*([^\r\n]+))/im, (m, indent, whole, img) => {
            const buildBlock = `${indent}build:\n${indent}  context: ./build\n${indent}  dockerfile: Dockerfile\n${indent}image: ${img.trim().replace(/^image:\s*/i, '')}`;
            return buildBlock;
          });
          await fs.writeFile(composePath, composeText, 'utf8');
          logger.info('Updated docker-compose.yml to prefer local build context (./build) to avoid image pulls');
        }
      } catch (err) {
        logger.warn('Failed to rewrite docker-compose to use local build: ' + String(err));
      }
    }

    // Now start docker compose using local build artifacts. Steps:
    // 1) cd into .docker
    // 2) run `docker compose up -d`
    // 3) if that fails with a port/bind conflict, run `docker compose down` and
    //    then `docker compose up -d` again
    try {
      await execa('docker', ['compose', 'up', '-d'], { cwd: dockerDir, stdio: 'inherit' });
      logger.success('Docker compose started');
    } catch (err) {
      const stderr = (err.stderr) ? String(err.stderr) : '';
      const stdout = (err.stdout) ? String(err.stdout) : '';
      const combined = (stderr + '\n' + stdout).toLowerCase();
      const portConflictRegex = /port is already allocated|address already in use|bind for .* failed|already in use/i;
      if (portConflictRegex.test(combined)) {
        logger.warn('Port conflict detected. Running `docker compose down` and retrying `docker compose up -d`.');
        try {
          await execa('docker', ['compose', 'down'], { cwd: dockerDir, stdio: 'inherit' });
        } catch (downErr) {
          logger.warn('`docker compose down` failed: ' + String(downErr));
        }
        try {
          await execa('docker', ['compose', 'up', '-d'], { cwd: dockerDir, stdio: 'inherit' });
          logger.success('Docker compose started after bringing the stack down');
        } catch (secondErr) {
          if (secondErr.stderr) logger.error('docker compose stderr:\n' + String(secondErr.stderr));
          if (secondErr.stdout) logger.info('docker compose stdout:\n' + String(secondErr.stdout));
          logger.error('docker compose failed after retry');
          process.exit(1);
        }
      } else {
        if (err.stderr) logger.error('docker compose stderr:\n' + String(err.stderr));
        if (err.stdout) logger.info('docker compose stdout:\n' + String(err.stdout));
        logger.error('docker compose failed');
        process.exit(1);
      }
    }

    const appUrl = cfg.appUrl || 'http://localhost:8080';
    const spinWait = ora(`Waiting for app at ${appUrl}`).start();
    try {
      await waitForApp(appUrl, cfg.waitRetries || 30, cfg.waitDelay || 2000, cfg.waitTimeout || 120);
      spinWait.succeed('App is available');
      logger.box(`Application available at ${appUrl}`, { borderColor: 'green' });
      // also print URL
      logger.success(appUrl);
      return;
    } catch (err) {
      spinWait.fail('App did not become available');
      logger.error(String(err) + '\nTry running `mxtest logs --follow` to debug');
      process.exit(1);
    }
  } catch (err) {
    logger.error('Run failed: ' + String(err));
    process.exit(1);
  }
};
